### ISSUE TITLE
[Feat]: Squire Client

### ISSUE THREAD

**Issue by djpiper28** [MonarchDevelopment/SquireDesktop#54]
## Description:
A complete asynchronous Squire Core client must be implemented to allow for the online service and desktop application to work together.

**Comment by TylerBloom** [comment]
There is already a generic client (generic in the computer-science sense) in the SquireSDK. That client is intended to bridge to the SC server that is usable on every platform. It will handle auth tracking, all the various endpoint paths, etc. The only thing that you need to provide is a "state", basically how the tournament data is stored. This will require you to use the SDK's `TournamentManager`, which is just a state-management wrapper around the normal `Tournament`.

As far as making it asynchronous, we can pretty easily make the client state lock-free. We will need to use some kind of async runtime (very like `tokio`) to send updates to the server.
